name = "taqsit-store"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"

[assets]
directory = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "taqsit-store-db"
database_id = "c97f6e35-c598-4fd1-a4ab-2f29c137c5e6"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "taqsit-store-images"
