import { type RouteConfig, layout, route, index } from '@react-router/dev/routes';

export default [
  layout('routes/store.tsx', [
    index('routes/home.tsx'),
    route('category/:slug', 'routes/category.tsx'),
    route('product/:id', 'routes/product.tsx'),
    route('search', 'routes/search.tsx'),
    route('katalog', 'routes/catalog.tsx'),
    route('brand/:slug', 'routes/brand.tsx'),
    route('chegirmalar', 'routes/deals.tsx'),
    route('savat', 'routes/cart.tsx'),
    route('kirish', 'routes/kirish.tsx'),
    route('kabinet', 'routes/kabinet.tsx'),
    route('page/:slug', 'routes/page.tsx'),
    route(':lang', 'routes/home.tsx', { id: 'home-lang' }),
    route(':lang/category/:slug', 'routes/category.tsx', { id: 'category-lang' }),
    route(':lang/product/:id', 'routes/product.tsx', { id: 'product-lang' }),
    route(':lang/search', 'routes/search.tsx', { id: 'search-lang' }),
    route(':lang/katalog', 'routes/catalog.tsx', { id: 'catalog-lang' }),
    route(':lang/brand/:slug', 'routes/brand.tsx', { id: 'brand-lang' }),
    route(':lang/chegirmalar', 'routes/deals.tsx', { id: 'deals-lang' }),
    route(':lang/savat', 'routes/cart.tsx', { id: 'cart-lang' }),
    route(':lang/kirish', 'routes/kirish.tsx', { id: 'kirish-lang' }),
    route(':lang/kabinet', 'routes/kabinet.tsx', { id: 'kabinet-lang' }),
    route(':lang/page/:slug', 'routes/page.tsx', { id: 'page-lang' }),
  ]),
  route('auth/google', 'routes/auth.google.tsx'),
  route('auth/google/callback', 'routes/auth.google.callback.tsx'),
  route('auth/telegram', 'routes/auth.telegram.tsx'),
  route('auth/email', 'routes/auth.email.tsx'),
  route('auth/logout', 'routes/auth.logout.tsx'),
  route('api/account', 'routes/api.account.tsx'),
  route('api/order', 'routes/api.order.tsx'),
  route('images/*', 'routes/images.$.tsx'),
  route('sitemap.xml', 'routes/sitemap[.]xml.tsx'),
  route('robots.txt', 'routes/robots[.]txt.tsx'),
  route('admin/*', 'routes/admin.tsx'),
  route('api/admin/login', 'routes/api.admin.login.tsx'),
  route('api/admin/logout', 'routes/api.admin.logout.tsx'),
  route('api/admin/me', 'routes/api.admin.me.tsx'),
  route('api/admin/account', 'routes/api.admin.account.tsx'),
  route('api/admin/products', 'routes/api.admin.products.tsx'),
  route('api/admin/products/:id', 'routes/api.admin.products.$id.tsx'),
  route('api/admin/categories', 'routes/api.admin.categories.tsx'),
  route('api/admin/categories/:id', 'routes/api.admin.categories.$id.tsx'),
  route('api/admin/brands', 'routes/api.admin.brands.tsx'),
  route('api/admin/brands/:id', 'routes/api.admin.brands.$id.tsx'),
  route('api/admin/models', 'routes/api.admin.models.tsx'),
  route('api/admin/models/:id', 'routes/api.admin.models.$id.tsx'),
  route('api/admin/settings', 'routes/api.admin.settings.tsx'),
  route('api/admin/upload', 'routes/api.admin.upload.tsx'),
  route('api/admin/banners', 'routes/api.admin.banners.tsx'),
  route('api/admin/banners/:id', 'routes/api.admin.banners.$id.tsx'),
  route('api/admin/pages', 'routes/api.admin.pages.tsx'),
  route('api/admin/pages/:id', 'routes/api.admin.pages.$id.tsx'),
  route('api/admin/site-config', 'routes/api.admin.site-config.tsx'),
  route('api/admin/orders', 'routes/api.admin.orders.tsx'),
  route('api/admin/orders/:id', 'routes/api.admin.orders.$id.tsx'),
  route('*', 'routes/not-found.tsx'),
] satisfies RouteConfig;
