import { type RouteConfig, layout, route, index } from '@react-router/dev/routes';

export default [
  layout('routes/store.tsx', [
    index('routes/home.tsx'),
    route('category/:slug', 'routes/category.tsx'),
    route('product/:id', 'routes/product.tsx'),
    route('search', 'routes/search.tsx'),
    route(':lang', 'routes/home.tsx', { id: 'home-lang' }),
    route(':lang/category/:slug', 'routes/category.tsx', { id: 'category-lang' }),
    route(':lang/product/:id', 'routes/product.tsx', { id: 'product-lang' }),
    route(':lang/search', 'routes/search.tsx', { id: 'search-lang' }),
  ]),
  route('api/products', 'routes/api.products.tsx'),
  route('api/products/:id', 'routes/api.products.$id.tsx'),
  route('api/categories', 'routes/api.categories.tsx'),
  route('api/settings', 'routes/api.settings.tsx'),
  route('images/*', 'routes/images.$.tsx'),
  route('admin/*', 'routes/admin.tsx'),
  route('api/admin/login', 'routes/api.admin.login.tsx'),
  route('api/admin/logout', 'routes/api.admin.logout.tsx'),
  route('api/admin/me', 'routes/api.admin.me.tsx'),
  route('api/admin/products', 'routes/api.admin.products.tsx'),
  route('api/admin/products/:id', 'routes/api.admin.products.$id.tsx'),
  route('api/admin/categories', 'routes/api.admin.categories.tsx'),
  route('api/admin/categories/:id', 'routes/api.admin.categories.$id.tsx'),
  route('api/admin/settings', 'routes/api.admin.settings.tsx'),
  route('api/admin/upload', 'routes/api.admin.upload.tsx'),
  route('*', 'routes/not-found.tsx'),
] satisfies RouteConfig;
