/**
 * O'zbekiston ma'muriy bo'linishi — manzil tanlash uchun (viloyat → tuman/shahar).
 *
 * Ma'lumot **qo'lda tuzilgan**: tayyor ochiq to'plamlar yo GPL, yo litsenziyasiz edi,
 * ya'ni bu repozitoriyga ko'chirib bo'lmasdi. Ro'yxat Vikipediyaning "Districts of
 * Uzbekistan" sahifasi bo'yicha tekshirilgan (ma'muriy bo'linish — fakt, ifoda emas).
 *
 * Tuman nomlari **faqat lotin yozuvida**: ular atoqli otlar va ikkala tilda ham shu
 * ko'rinishda ishlatiladi (ko'chadagi taxtalarda ham shunday). Viloyat nomlari uz/ru.
 * Ruscha tuman nomlari kerak bo'lsa `districts[].nameRu` qo'shiladi — tuzilma tayyor.
 *
 * `id` lar **barqaror**: buyurtma manzili matn nusxasi sifatida saqlanadi, lekin
 * profildagi manzil id bo'yicha o'qiladi, shuning uchun id o'zgartirilmaydi.
 */
export interface UzDistrict {
  id: string;
  name: string;
}

export interface UzRegion {
  id: string;
  name: string;
  nameRu: string;
  districts: UzDistrict[];
}

export const UZ_REGIONS: UzRegion[] = [
  {
    id: 'qoraqalpogiston',
    name: 'Qoraqalpogʻiston Respublikasi',
    nameRu: 'Республика Каракалпакстан',
    districts: [
      { id: 'amudaryo', name: 'Amudaryo' },
      { id: 'beruniy', name: 'Beruniy' },
      { id: 'chimboy', name: 'Chimboy' },
      { id: 'ellikqala', name: 'Ellikqalʼa' },
      { id: 'kegeyli', name: 'Kegeyli' },
      { id: 'moynoq', name: 'Moʻynoq' },
      { id: 'nukus', name: 'Nukus' },
      { id: 'qanlikol', name: 'Qanlikoʻl' },
      { id: 'qongirot', name: 'Qoʻngʻirot' },
      { id: 'qoraozak', name: 'Qoraoʻzak' },
      { id: 'shumanay', name: 'Shumanay' },
      { id: 'taxtakopir', name: 'Taxtakoʻpir' },
      { id: 'tortkol', name: 'Toʻrtkoʻl' },
      { id: 'xojayli', name: 'Xoʻjayli' },
      { id: 'taxiatosh', name: 'Taxiatosh' },
      { id: 'bozatov', name: 'Boʻzatov' },
      { id: 'nukus-shahri', name: 'Nukus shahri' },
    ],
  },
  {
    id: 'andijon',
    name: 'Andijon viloyati',
    nameRu: 'Андижанская область',
    districts: [
      { id: 'andijon', name: 'Andijon' },
      { id: 'asaka', name: 'Asaka' },
      { id: 'baliqchi', name: 'Baliqchi' },
      { id: 'boston', name: 'Boʻston' },
      { id: 'buloqboshi', name: 'Buloqboshi' },
      { id: 'izboskan', name: 'Izboskan' },
      { id: 'jalaquduq', name: 'Jalaquduq' },
      { id: 'xojaobod', name: 'Xoʻjaobod' },
      { id: 'qorgontepa', name: 'Qoʻrgʻontepa' },
      { id: 'marhamat', name: 'Marhamat' },
      { id: 'oltinkol', name: 'Oltinkoʻl' },
      { id: 'paxtaobod', name: 'Paxtaobod' },
      { id: 'shahrixon', name: 'Shahrixon' },
      { id: 'ulugnor', name: 'Ulugʻnor' },
      { id: 'andijon-shahri', name: 'Andijon shahri' },
      { id: 'xonobod-shahri', name: 'Xonobod shahri' },
    ],
  },
  {
    id: 'buxoro',
    name: 'Buxoro viloyati',
    nameRu: 'Бухарская область',
    districts: [
      { id: 'olot', name: 'Olot' },
      { id: 'buxoro', name: 'Buxoro' },
      { id: 'gijduvon', name: 'Gʻijduvon' },
      { id: 'jondor', name: 'Jondor' },
      { id: 'kogon', name: 'Kogon' },
      { id: 'qorakol', name: 'Qorakoʻl' },
      { id: 'qorovulbozor', name: 'Qorovulbozor' },
      { id: 'peshku', name: 'Peshku' },
      { id: 'romitan', name: 'Romitan' },
      { id: 'shofirkon', name: 'Shofirkon' },
      { id: 'vobkent', name: 'Vobkent' },
      { id: 'buxoro-shahri', name: 'Buxoro shahri' },
      { id: 'kogon-shahri', name: 'Kogon shahri' },
    ],
  },
  {
    id: 'fargona',
    name: 'Fargʻona viloyati',
    nameRu: 'Ферганская область',
    districts: [
      { id: 'oltiariq', name: 'Oltiariq' },
      { id: 'bagdod', name: 'Bagʻdod' },
      { id: 'beshariq', name: 'Beshariq' },
      { id: 'buvayda', name: 'Buvayda' },
      { id: 'dangara', name: 'Dangʻara' },
      { id: 'fargona', name: 'Fargʻona' },
      { id: 'furqat', name: 'Furqat' },
      { id: 'qoshtepa', name: 'Qoʻshtepa' },
      { id: 'quva', name: 'Quva' },
      { id: 'rishton', name: 'Rishton' },
      { id: 'sox', name: 'Soʻx' },
      { id: 'toshloq', name: 'Toshloq' },
      { id: 'uchkoprik', name: 'Uchkoʻprik' },
      { id: 'ozbekiston', name: 'Oʻzbekiston' },
      { id: 'yozyovon', name: 'Yozyovon' },
      { id: 'fargona-shahri', name: 'Fargʻona shahri' },
      { id: 'margilon-shahri', name: 'Margʻilon shahri' },
      { id: 'qoqon-shahri', name: 'Qoʻqon shahri' },
      { id: 'quvasoy-shahri', name: 'Quvasoy shahri' },
    ],
  },
  {
    id: 'jizzax',
    name: 'Jizzax viloyati',
    nameRu: 'Джизакская область',
    districts: [
      { id: 'arnasoy', name: 'Arnasoy' },
      { id: 'baxmal', name: 'Baxmal' },
      { id: 'dostlik', name: 'Doʻstlik' },
      { id: 'forish', name: 'Forish' },
      { id: 'gallaorol', name: 'Gʻallaorol' },
      { id: 'sharof-rashidov', name: 'Sharof Rashidov' },
      { id: 'mirzachol', name: 'Mirzachoʻl' },
      { id: 'paxtakor', name: 'Paxtakor' },
      { id: 'yangiobod', name: 'Yangiobod' },
      { id: 'zomin', name: 'Zomin' },
      { id: 'zafarobod', name: 'Zafarobod' },
      { id: 'zarbdor', name: 'Zarbdor' },
      { id: 'jizzax-shahri', name: 'Jizzax shahri' },
    ],
  },
  {
    id: 'xorazm',
    name: 'Xorazm viloyati',
    nameRu: 'Хорезмская область',
    districts: [
      { id: 'bogot', name: 'Bogʻot' },
      { id: 'gurlan', name: 'Gurlan' },
      { id: 'xonqa', name: 'Xonqa' },
      { id: 'hazorasp', name: 'Hazorasp' },
      { id: 'xiva', name: 'Xiva' },
      { id: 'qoshkopir', name: 'Qoʻshkoʻpir' },
      { id: 'shovot', name: 'Shovot' },
      { id: 'urganch', name: 'Urganch' },
      { id: 'yangiariq', name: 'Yangiariq' },
      { id: 'yangibozor', name: 'Yangibozor' },
      { id: 'tuproqqala', name: 'Tuproqqalʼa' },
      { id: 'urganch-shahri', name: 'Urganch shahri' },
      { id: 'xiva-shahri', name: 'Xiva shahri' },
    ],
  },
  {
    id: 'namangan',
    name: 'Namangan viloyati',
    nameRu: 'Наманганская область',
    districts: [
      { id: 'chortoq', name: 'Chortoq' },
      { id: 'chust', name: 'Chust' },
      { id: 'kosonsoy', name: 'Kosonsoy' },
      { id: 'mingbuloq', name: 'Mingbuloq' },
      { id: 'namangan', name: 'Namangan' },
      { id: 'norin', name: 'Norin' },
      { id: 'pop', name: 'Pop' },
      { id: 'toraqorgon', name: 'Toʻraqoʻrgʻon' },
      { id: 'uchqorgon', name: 'Uchqoʻrgʻon' },
      { id: 'uychi', name: 'Uychi' },
      { id: 'yangiqorgon', name: 'Yangiqoʻrgʻon' },
      { id: 'namangan-shahri', name: 'Namangan shahri' },
    ],
  },
  {
    id: 'navoiy',
    name: 'Navoiy viloyati',
    nameRu: 'Навоийская область',
    districts: [
      { id: 'konimex', name: 'Konimex' },
      { id: 'qiziltepa', name: 'Qiziltepa' },
      { id: 'xatirchi', name: 'Xatirchi' },
      { id: 'navbahor', name: 'Navbahor' },
      { id: 'karmana', name: 'Karmana' },
      { id: 'nurota', name: 'Nurota' },
      { id: 'tomdi', name: 'Tomdi' },
      { id: 'uchquduq', name: 'Uchquduq' },
      { id: 'navoiy-shahri', name: 'Navoiy shahri' },
      { id: 'zarafshon-shahri', name: 'Zarafshon shahri' },
    ],
  },
  {
    id: 'qashqadaryo',
    name: 'Qashqadaryo viloyati',
    nameRu: 'Кашкадарьинская область',
    districts: [
      { id: 'chiroqchi', name: 'Chiroqchi' },
      { id: 'dehqonobod', name: 'Dehqonobod' },
      { id: 'guzor', name: 'Gʻuzor' },
      { id: 'qamashi', name: 'Qamashi' },
      { id: 'qarshi', name: 'Qarshi' },
      { id: 'koson', name: 'Koson' },
      { id: 'kasbi', name: 'Kasbi' },
      { id: 'kitob', name: 'Kitob' },
      { id: 'mirishkor', name: 'Mirishkor' },
      { id: 'muborak', name: 'Muborak' },
      { id: 'nishon', name: 'Nishon' },
      { id: 'shahrisabz', name: 'Shahrisabz' },
      { id: 'yakkabog', name: 'Yakkabogʻ' },
      { id: 'kokdala', name: 'Koʻkdala' },
      { id: 'qarshi-shahri', name: 'Qarshi shahri' },
      { id: 'shahrisabz-shahri', name: 'Shahrisabz shahri' },
    ],
  },
  {
    id: 'samarqand',
    name: 'Samarqand viloyati',
    nameRu: 'Самаркандская область',
    districts: [
      { id: 'bulungur', name: 'Bulungʻur' },
      { id: 'ishtixon', name: 'Ishtixon' },
      { id: 'jomboy', name: 'Jomboy' },
      { id: 'kattaqorgon', name: 'Kattaqoʻrgʻon' },
      { id: 'qoshrabot', name: 'Qoʻshrabot' },
      { id: 'narpay', name: 'Narpay' },
      { id: 'nurobod', name: 'Nurobod' },
      { id: 'oqdaryo', name: 'Oqdaryo' },
      { id: 'paxtachi', name: 'Paxtachi' },
      { id: 'payariq', name: 'Payariq' },
      { id: 'pastdargom', name: 'Pastdargʻom' },
      { id: 'samarqand', name: 'Samarqand' },
      { id: 'toyloq', name: 'Toyloq' },
      { id: 'urgut', name: 'Urgut' },
      { id: 'samarqand-shahri', name: 'Samarqand shahri' },
      { id: 'kattaqorgon-shahri', name: 'Kattaqoʻrgʻon shahri' },
    ],
  },
  {
    id: 'sirdaryo',
    name: 'Sirdaryo viloyati',
    nameRu: 'Сырдарьинская область',
    districts: [
      { id: 'oqoltin', name: 'Oqoltin' },
      { id: 'boyovut', name: 'Boyovut' },
      { id: 'guliston', name: 'Guliston' },
      { id: 'xovos', name: 'Xovos' },
      { id: 'mirzaobod', name: 'Mirzaobod' },
      { id: 'sardoba', name: 'Sardoba' },
      { id: 'sayxunobod', name: 'Sayxunobod' },
      { id: 'sirdaryo', name: 'Sirdaryo' },
      { id: 'guliston-shahri', name: 'Guliston shahri' },
      { id: 'shirin-shahri', name: 'Shirin shahri' },
      { id: 'yangiyer-shahri', name: 'Yangiyer shahri' },
    ],
  },
  {
    id: 'surxondaryo',
    name: 'Surxondaryo viloyati',
    nameRu: 'Сурхандарьинская область',
    districts: [
      { id: 'angor', name: 'Angor' },
      { id: 'bandixon', name: 'Bandixon' },
      { id: 'boysun', name: 'Boysun' },
      { id: 'denov', name: 'Denov' },
      { id: 'jarqorgon', name: 'Jarqoʻrgʻon' },
      { id: 'qiziriq', name: 'Qiziriq' },
      { id: 'qumqorgon', name: 'Qumqoʻrgʻon' },
      { id: 'muzrabot', name: 'Muzrabot' },
      { id: 'oltinsoy', name: 'Oltinsoy' },
      { id: 'sariosiyo', name: 'Sariosiyo' },
      { id: 'sherobod', name: 'Sherobod' },
      { id: 'shorchi', name: 'Shoʻrchi' },
      { id: 'termiz', name: 'Termiz' },
      { id: 'uzun', name: 'Uzun' },
      { id: 'termiz-shahri', name: 'Termiz shahri' },
    ],
  },
  {
    id: 'toshkent',
    name: 'Toshkent viloyati',
    nameRu: 'Ташкентская область',
    districts: [
      { id: 'bekobod', name: 'Bekobod' },
      { id: 'bostonliq', name: 'Boʻstonliq' },
      { id: 'boka', name: 'Boʻka' },
      { id: 'chinoz', name: 'Chinoz' },
      { id: 'qibray', name: 'Qibray' },
      { id: 'ohangaron', name: 'Ohangaron' },
      { id: 'oqqorgon', name: 'Oqqoʻrgʻon' },
      { id: 'parkent', name: 'Parkent' },
      { id: 'piskent', name: 'Piskent' },
      { id: 'quyichirchiq', name: 'Quyichirchiq' },
      { id: 'zangiota', name: 'Zangiota' },
      { id: 'ortachirchiq', name: 'Oʻrtachirchiq' },
      { id: 'yangiyol', name: 'Yangiyoʻl' },
      { id: 'yuqorichirchiq', name: 'Yuqorichirchiq' },
      { id: 'toshkent-tumani', name: 'Toshkent tumani' },
      { id: 'angren-shahri', name: 'Angren shahri' },
      { id: 'bekobod-shahri', name: 'Bekobod shahri' },
      { id: 'chirchiq-shahri', name: 'Chirchiq shahri' },
      { id: 'nurafshon-shahri', name: 'Nurafshon shahri' },
      { id: 'olmaliq-shahri', name: 'Olmaliq shahri' },
      { id: 'ohangaron-shahri', name: 'Ohangaron shahri' },
      { id: 'yangiyol-shahri', name: 'Yangiyoʻl shahri' },
    ],
  },
  {
    id: 'toshkent-shahri',
    name: 'Toshkent shahri',
    nameRu: 'город Ташкент',
    districts: [
      { id: 'bektemir', name: 'Bektemir' },
      { id: 'chilonzor', name: 'Chilonzor' },
      { id: 'yashnobod', name: 'Yashnobod' },
      { id: 'mirobod', name: 'Mirobod' },
      { id: 'mirzo-ulugbek', name: 'Mirzo Ulugʻbek' },
      { id: 'sergeli', name: 'Sergeli' },
      { id: 'shayxontohur', name: 'Shayxontohur' },
      { id: 'olmazor', name: 'Olmazor' },
      { id: 'uchtepa', name: 'Uchtepa' },
      { id: 'yakkasaroy', name: 'Yakkasaroy' },
      { id: 'yunusobod', name: 'Yunusobod' },
      { id: 'yangihayot', name: 'Yangihayot' },
    ],
  },
];

export function regionById(id: string): UzRegion | undefined {
  return UZ_REGIONS.find((r) => r.id === id);
}

export function districtById(regionId: string, districtId: string): UzDistrict | undefined {
  return regionById(regionId)?.districts.find((d) => d.id === districtId);
}
