const MESSAGES: Record<string, string> = {
  imageUrl_required: 'Banner rasmi majburiy',
  link_invalid: "Link '/' yoki 'https://' bilan boshlanishi kerak",
  slug_required: 'Slug majburiy',
  slug_invalid: "Slug faqat kichik lotin harflari, raqam va '-' dan iborat bo'lishi kerak",
  slug_taken: 'Bu slug band — boshqasini tanlang',
  title_uz_required: "Sarlavha (o'zbek lotin) majburiy",
  title_ru_required: 'Sarlavha (rus) majburiy',
  name_required: 'Nomi majburiy',
  phone_required: 'Telefon majburiy',
  id_taken: 'Bu model allaqachon mavjud',
  brandId_required: 'Brend majburiy',
  categoryId_required: 'Kategoriya majburiy',
  price_positive: "Narx 0 dan katta bo'lishi kerak",
  variant_price_positive: "Variant narxi 0 dan katta bo'lishi kerak",
  category_invalid: "Kategoriya noto'g'ri",
  current_password_required: 'Joriy parolni kiriting',
  invalid_current_password: "Joriy parol noto'g'ri",
  username_too_short: "Login kamida 3 belgidan iborat bo'lishi kerak",
  password_too_short: "Yangi parol kamida 8 belgidan iborat bo'lishi kerak",
  nothing_to_update: "O'zgartirish uchun ma'lumot yo'q",
  not_initialized: "Admin sozlanmagan (migratsiya qo'llanganmi?)",
  too_many_attempts: "Urinishlar ko'payib ketdi — birozdan so'ng qayta urining",
  variant_duplicate: "Bir xil kombinatsiyali ikkita variant bor",
  variant_combination_incomplete: "Har bir variantda barcha o'lchov qiymatlari tanlanishi kerak",
  variant_value_unknown: "Variantda option'da mavjud bo'lmagan qiymat tanlangan",
  option_names_unique: "Option nomlari takrorlanmasligi kerak",
  option_values_required: "Har bir option kamida bitta qiymatga ega bo'lishi kerak",
  condition_invalid: "Holat qiymati noto'g'ri",
  unauthorized: 'Sessiya tugagan — qaytadan kiring',
  down_payment_range: "Boshlang'ich to'lov 0–100% oralig'ida bo'lishi kerak",
  usd_positive: "Dollar kursi 0 dan katta bo'lishi kerak",
  terms_required: 'Kamida bitta muddat kiriting',
  months_positive: "Oy soni 0 dan katta bo'lishi kerak",
  markup_negative: "Ustama manfiy bo'lishi mumkin emas",
  telegram_invalid: "Telegram havolasi '/' yoki 'https://' bilan boshlanishi kerak",
  instagram_invalid: "Instagram havolasi '/' yoki 'https://' bilan boshlanishi kerak",
  whatsapp_invalid: "WhatsApp havolasi '/' yoki 'https://' bilan boshlanishi kerak",
  images_limit: "Rasmlar soni chegaradan oshdi",
  specs_limit: "Xususiyatlar soni chegaradan oshdi",
  options_limit: "Opsiyalar soni chegaradan oshdi",
  option_values_limit: "Opsiya qiymatlari soni chegaradan oshdi",
  variants_limit: "Variantlar soni chegaradan oshdi",
};

export function errText(e: unknown): string {
  const code = e instanceof Error ? e.message : '';
  return MESSAGES[code] ?? (code || 'Xatolik yuz berdi');
}
